// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ilp_efti_connector.Infrastructure.Persistence;

#nullable disable

namespace ilp_efti_connector.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EftiConnectorDbContext))]
    [Migration("20260303122316_SeedFrontendSource")]
    partial class SeedFrontendSource
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ilp_efti_connector.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("action_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewValueJson")
                        .HasColumnType("JSON")
                        .HasColumnName("new_value_json");

                    b.Property<string>("OldValueJson")
                        .HasColumnType("JSON")
                        .HasColumnName("old_value_json");

                    b.Property<Guid?>("PerformedBySourceId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("performed_by_source_id");

                    b.Property<Guid?>("PerformedByUserId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("performed_by_user_id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EntityId");

                    b.HasIndex("EntityType");

                    b.HasIndex("PerformedByUserId");

                    b.HasIndex("EntityType", "EntityId", "CreatedAt");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("ilp_efti_connector.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("id");

                    b.Property<bool>("AutoCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("auto_created");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("business_name");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("contact_email");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("customer_code");

                    b.Property<string>("EoriCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("eori_code");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("source_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("updated_at");

                    b.Property<string>("VatNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("vat_number");

                    b.HasKey("Id");

                    b.HasIndex("CustomerCode")
                        .IsUnique();

                    b.HasIndex("SourceId");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("ilp_efti_connector.Domain.Entities.CustomerDestination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("id");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("address_line1");

                    b.Property<bool>("AutoCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("auto_created");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("city");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("CHAR(2)")
                        .HasColumnName("country_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("customer_id");

                    b.Property<string>("DestinationCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("destination_code");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("label");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("postal_code");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("province");

                    b.Property<string>("UnLocode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("un_locode");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DestinationCode")
                        .IsUnique();

                    b.ToTable("customer_destinations", (string)null);
                });

            modelBuilder.Entity("ilp_efti_connector.Domain.Entities.EftiMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("acknowledged_at");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("created_at");

                    b.Property<string>("DatasetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("dataset_type");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("direction");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("external_id");

                    b.Property<string>("ExternalUuid")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("external_uuid");

                    b.Property<string>("GatewayProvider")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("gateway_provider");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("next_retry_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("JSON")
                        .HasColumnName("payload_json");

                    b.Property<short>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("retry_count");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("sent_at");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("source_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("status");

                    b.Property<Guid>("TransportOperationId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("transport_operation_id");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ExternalId");

                    b.HasIndex("NextRetryAt");

                    b.HasIndex("SourceId");

                    b.HasIndex("Status");

                    b.HasIndex("TransportOperationId");

                    b.ToTable("efti_messages", (string)null);
                });

            modelBuilder.Entity("ilp_efti_connector.Domain.Entities.Source", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("id");

                    b.Property<string>("ApiKeyHash")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("api_key_hash");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<string>("ConfigJson")
                        .HasColumnType("JSON")
                        .HasColumnName("config_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("sources", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "TMS_TEST",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Sorgente di Test",
                            Type = "TMS"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "TEST_FRONTEND",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Form di test per inserimento",
                            Type = "MANUAL"
                        });
                });

            modelBuilder.Entity("ilp_efti_connector.Domain.Entities.TransportCarrier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("id");

                    b.Property<string>("EoriCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("eori_code");

                    b.Property<string>("EquipmentCategory")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("equipment_category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("name");

                    b.Property<string>("PlayerType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("player_type");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<string>("TaxRegistration")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tax_registration");

                    b.Property<string>("TractorPlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tractor_plate");

                    b.Property<Guid>("TransportOperationId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("transport_operation_id");

                    b.HasKey("Id");

                    b.HasIndex("TransportOperationId");

                    b.ToTable("transport_carriers", (string)null);
                });

            modelBuilder.Entity("ilp_efti_connector.Domain.Entities.TransportConsignee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("id");

                    b.Property<string>("EoriCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("eori_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("name");

                    b.Property<string>("PlayerType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("player_type");

                    b.Property<string>("TaxRegistration")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tax_registration");

                    b.Property<Guid>("TransportOperationId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("transport_operation_id");

                    b.HasKey("Id");

                    b.HasIndex("TransportOperationId")
                        .IsUnique();

                    b.ToTable("transport_consignees", (string)null);
                });

            modelBuilder.Entity("ilp_efti_connector.Domain.Entities.TransportConsignmentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("id");

                    b.Property<int>("TotalItemQuantity")
                        .HasColumnType("int")
                        .HasColumnName("total_item_quantity");

                    b.Property<decimal?>("TotalVolume")
                        .HasColumnType("DECIMAL(10,3)")
                        .HasColumnName("total_volume");

                    b.Property<decimal>("TotalWeight")
                        .HasColumnType("DECIMAL(10,3)")
                        .HasColumnName("total_weight");

                    b.Property<Guid>("TransportOperationId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("transport_operation_id");

                    b.HasKey("Id");

                    b.HasIndex("TransportOperationId")
                        .IsUnique();

                    b.ToTable("transport_consignment_items", (string)null);
                });

            modelBuilder.Entity("ilp_efti_connector.Domain.Entities.TransportDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcceptanceDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("acceptance_date");

                    b.Property<string>("CargoType")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("cargo_type");

                    b.Property<string>("Incoterms")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("incoterms");

                    b.Property<Guid>("TransportOperationId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("transport_operation_id");

                    b.HasKey("Id");

                    b.HasIndex("TransportOperationId")
                        .IsUnique();

                    b.ToTable("transport_details", (string)null);
                });

            modelBuilder.Entity("ilp_efti_connector.Domain.Entities.TransportOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("customer_id");

                    b.Property<string>("DatasetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("dataset_type");

                    b.Property<Guid?>("DestinationId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("destination_id");

                    b.Property<string>("Hashcode")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("hashcode");

                    b.Property<string>("HashcodeAlgorithm")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("hashcode_algorithm");

                    b.Property<string>("OperationCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("operation_code");

                    b.Property<string>("RawPayloadJson")
                        .HasColumnType("JSON")
                        .HasColumnName("raw_payload_json");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("source_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DestinationId");

                    b.HasIndex("OperationCode");

                    b.HasIndex("SourceId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("transport_operations", (string)null);
                });

            modelBuilder.Entity("ilp_efti_connector.Domain.Entities.TransportPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("ConsignmentItemId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("consignment_item_id");

                    b.Property<decimal?>("GrossVolume")
                        .HasColumnType("DECIMAL(10,3)")
                        .HasColumnName("gross_volume");

                    b.Property<decimal>("GrossWeight")
                        .HasColumnType("DECIMAL(10,3)")
                        .HasColumnName("gross_weight");

                    b.Property<int>("ItemQuantity")
                        .HasColumnType("int")
                        .HasColumnName("item_quantity");

                    b.Property<string>("ShippingMarks")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("shipping_marks");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<string>("TypeCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type_code");

                    b.HasKey("Id");

                    b.HasIndex("ConsignmentItemId");

                    b.ToTable("transport_packages", (string)null);
                });

            modelBuilder.Entity("ilp_efti_connector.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("KeycloakId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("keycloak_id");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("last_login_at");

                    b.Property<string>("RolesJson")
                        .HasColumnType("JSON")
                        .HasColumnName("roles_json");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("KeycloakId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ilp_efti_connector.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("ilp_efti_connector.Domain.Entities.User", "PerformedByUser")
                        .WithMany("AuditLogs")
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PerformedByUser");
                });

            modelBuilder.Entity("ilp_efti_connector.Domain.Entities.Customer", b =>
                {
                    b.HasOne("ilp_efti_connector.Domain.Entities.Source", "Source")
                        .WithMany("Customers")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Source");
                });

            modelBuilder.Entity("ilp_efti_connector.Domain.Entities.CustomerDestination", b =>
                {
                    b.HasOne("ilp_efti_connector.Domain.Entities.Customer", "Customer")
                        .WithMany("Destinations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ilp_efti_connector.Domain.Entities.EftiMessage", b =>
                {
                    b.HasOne("ilp_efti_connector.Domain.Entities.Source", "Source")
                        .WithMany("EftiMessages")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ilp_efti_connector.Domain.Entities.TransportOperation", "TransportOperation")
                        .WithMany("EftiMessages")
                        .HasForeignKey("TransportOperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");

                    b.Navigation("TransportOperation");
                });

            modelBuilder.Entity("ilp_efti_connector.Domain.Entities.TransportCarrier", b =>
                {
                    b.HasOne("ilp_efti_connector.Domain.Entities.TransportOperation", "TransportOperation")
                        .WithMany("Carriers")
                        .HasForeignKey("TransportOperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ilp_efti_connector.Domain.ValueObjects.PostalAddress", "PostalAddress", b1 =>
                        {
                            b1.Property<Guid>("TransportCarrierId")
                                .HasColumnType("CHAR(36)");

                            b1.Property<string>("CityName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("city_name");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasColumnType("CHAR(2)")
                                .HasColumnName("country_code");

                            b1.Property<string>("CountryName")
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("country_name");

                            b1.Property<string>("PostCode")
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("post_code");

                            b1.Property<string>("StreetName")
                                .HasMaxLength(300)
                                .HasColumnType("varchar(300)")
                                .HasColumnName("street_name");

                            b1.HasKey("TransportCarrierId");

                            b1.ToTable("transport_carriers");

                            b1.WithOwner()
                                .HasForeignKey("TransportCarrierId");
                        });

                    b.Navigation("PostalAddress")
                        .IsRequired();

                    b.Navigation("TransportOperation");
                });

            modelBuilder.Entity("ilp_efti_connector.Domain.Entities.TransportConsignee", b =>
                {
                    b.HasOne("ilp_efti_connector.Domain.Entities.TransportOperation", "TransportOperation")
                        .WithOne("Consignee")
                        .HasForeignKey("ilp_efti_connector.Domain.Entities.TransportConsignee", "TransportOperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ilp_efti_connector.Domain.ValueObjects.PostalAddress", "PostalAddress", b1 =>
                        {
                            b1.Property<Guid>("TransportConsigneeId")
                                .HasColumnType("CHAR(36)");

                            b1.Property<string>("CityName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("city_name");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasColumnType("CHAR(2)")
                                .HasColumnName("country_code");

                            b1.Property<string>("CountryName")
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("country_name");

                            b1.Property<string>("PostCode")
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("post_code");

                            b1.Property<string>("StreetName")
                                .HasMaxLength(300)
                                .HasColumnType("varchar(300)")
                                .HasColumnName("street_name");

                            b1.HasKey("TransportConsigneeId");

                            b1.ToTable("transport_consignees");

                            b1.WithOwner()
                                .HasForeignKey("TransportConsigneeId");
                        });

                    b.Navigation("PostalAddress")
                        .IsRequired();

                    b.Navigation("TransportOperation");
                });

            modelBuilder.Entity("ilp_efti_connector.Domain.Entities.TransportConsignmentItem", b =>
                {
                    b.HasOne("ilp_efti_connector.Domain.Entities.TransportOperation", "TransportOperation")
                        .WithOne("ConsignmentItem")
                        .HasForeignKey("ilp_efti_connector.Domain.Entities.TransportConsignmentItem", "TransportOperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransportOperation");
                });

            modelBuilder.Entity("ilp_efti_connector.Domain.Entities.TransportDetail", b =>
                {
                    b.HasOne("ilp_efti_connector.Domain.Entities.TransportOperation", "TransportOperation")
                        .WithOne("Detail")
                        .HasForeignKey("ilp_efti_connector.Domain.Entities.TransportDetail", "TransportOperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ilp_efti_connector.Domain.ValueObjects.PostalAddress", "AcceptanceAddress", b1 =>
                        {
                            b1.Property<Guid>("TransportDetailId")
                                .HasColumnType("CHAR(36)");

                            b1.Property<string>("CityName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("acceptance_city_name");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasColumnType("CHAR(2)")
                                .HasColumnName("acceptance_country_code");

                            b1.Property<string>("CountryName")
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("acceptance_country_name");

                            b1.Property<string>("PostCode")
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("acceptance_post_code");

                            b1.Property<string>("StreetName")
                                .HasMaxLength(300)
                                .HasColumnType("varchar(300)")
                                .HasColumnName("acceptance_street_name");

                            b1.HasKey("TransportDetailId");

                            b1.ToTable("transport_details");

                            b1.WithOwner()
                                .HasForeignKey("TransportDetailId");
                        });

                    b.OwnsOne("ilp_efti_connector.Domain.ValueObjects.PostalAddress", "ReceiptAddress", b1 =>
                        {
                            b1.Property<Guid>("TransportDetailId")
                                .HasColumnType("CHAR(36)");

                            b1.Property<string>("CityName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("receipt_city_name");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasColumnType("CHAR(2)")
                                .HasColumnName("receipt_country_code");

                            b1.Property<string>("CountryName")
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("receipt_country_name");

                            b1.Property<string>("PostCode")
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("receipt_post_code");

                            b1.Property<string>("StreetName")
                                .HasMaxLength(300)
                                .HasColumnType("varchar(300)")
                                .HasColumnName("receipt_street_name");

                            b1.HasKey("TransportDetailId");

                            b1.ToTable("transport_details");

                            b1.WithOwner()
                                .HasForeignKey("TransportDetailId");
                        });

                    b.Navigation("AcceptanceAddress")
                        .IsRequired();

                    b.Navigation("ReceiptAddress")
                        .IsRequired();

                    b.Navigation("TransportOperation");
                });

            modelBuilder.Entity("ilp_efti_connector.Domain.Entities.TransportOperation", b =>
                {
                    b.HasOne("ilp_efti_connector.Domain.Entities.User", "CreatedByUser")
                        .WithMany("CreatedTransportOperations")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ilp_efti_connector.Domain.Entities.Customer", "Customer")
                        .WithMany("TransportOperations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ilp_efti_connector.Domain.Entities.CustomerDestination", "Destination")
                        .WithMany("TransportOperations")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ilp_efti_connector.Domain.Entities.Source", "Source")
                        .WithMany("TransportOperations")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ilp_efti_connector.Domain.Entities.User", "UpdatedByUser")
                        .WithMany("UpdatedTransportOperations")
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");

                    b.Navigation("Customer");

                    b.Navigation("Destination");

                    b.Navigation("Source");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("ilp_efti_connector.Domain.Entities.TransportPackage", b =>
                {
                    b.HasOne("ilp_efti_connector.Domain.Entities.TransportConsignmentItem", "ConsignmentItem")
                        .WithMany("Packages")
                        .HasForeignKey("ConsignmentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsignmentItem");
                });

            modelBuilder.Entity("ilp_efti_connector.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Destinations");

                    b.Navigation("TransportOperations");
                });

            modelBuilder.Entity("ilp_efti_connector.Domain.Entities.CustomerDestination", b =>
                {
                    b.Navigation("TransportOperations");
                });

            modelBuilder.Entity("ilp_efti_connector.Domain.Entities.Source", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("EftiMessages");

                    b.Navigation("TransportOperations");
                });

            modelBuilder.Entity("ilp_efti_connector.Domain.Entities.TransportConsignmentItem", b =>
                {
                    b.Navigation("Packages");
                });

            modelBuilder.Entity("ilp_efti_connector.Domain.Entities.TransportOperation", b =>
                {
                    b.Navigation("Carriers");

                    b.Navigation("Consignee");

                    b.Navigation("ConsignmentItem");

                    b.Navigation("Detail");

                    b.Navigation("EftiMessages");
                });

            modelBuilder.Entity("ilp_efti_connector.Domain.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("CreatedTransportOperations");

                    b.Navigation("UpdatedTransportOperations");
                });
#pragma warning restore 612, 618
        }
    }
}
